name: "Download Button Action"

on:
  release:
    types:
      - published
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Get latest release
        id: get-latest-release
        uses: InsonusK/get-latest-release@v1.0.1
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
          view_top: 1

      - name: Readme Download Button Action
        env:
          GITHUB_USER: "sixdsix"
          REPO: "SteamDeckCInstaller"
          FORMAT: "tar.gz"
          VERSION: ${{ steps.get-latest-release.outputs.tag_name }}
          COLOR: "blue"
          BEGIN_TAG: "<!-- BEGIN LATEST DOWNLOAD BUTTON -->"
          END_TAG: "<!-- END LATEST DOWNLOAD BUTTON -->"
        run: |
          # Replace the download button between BEGIN_TAG and END_TAG in README.md
          UPDATE=$(cat README.md | perl -0777 -pe "s#(${BEGIN_TAG})(?:.|\\n)*?(${END_TAG})#\${1}\n[![Download ${FORMAT}](https://custom-icon-badges.demolab.com/badge/-Download-${COLOR}?style=for-the-badge&logo=download&logoColor=white \"Download ${FORMAT}\")](https://github.com/${GITHUB_USER}/${REPO}/archive/${VERSION}.${FORMAT})\n\${2}#g")
          echo "${UPDATE}" > README.md

      - uses: EndBug/add-and-commit@v7
        with:
          message: "docs(readme): Bump download button version to ${{ steps.get-latest-release.outputs.tag_name }}"
          default_author: github_actions
          branch: main
